// Code generated by "stringer -type=LoginState actor.go"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LoginStateStart-0]
	_ = x[LoginStateWantUser-1]
	_ = x[LoginStateWantPwd-2]
	_ = x[LoginStateFailed-3]
	_ = x[LoginStateMaxFailed-4]
	_ = x[LoginStateLoggedIn-5]
}

const _LoginState_name = "LoginStateStartLoginStateWantUserLoginStateWantPwdLoginStateFailedLoginStateMaxFailedLoginStateLoggedIn"

var _LoginState_index = [...]uint8{0, 15, 33, 50, 66, 85, 103}

func (i LoginState) String() string {
	if i < 0 || i >= LoginState(len(_LoginState_index)-1) {
		return "LoginState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LoginState_name[_LoginState_index[i]:_LoginState_index[i+1]]
}
